services:
  mysql-server:
    image: mysql:8.0
    container_name: MySQL-API
    environment:
      MYSQL_DATABASE: API_ujikom
      MYSQL_USER: api_ujikom
      MYSQL_PASSWORD: api_ujikom
      MYSQL_ROOT_PASSWORD: passwordroot
    ports:
      - "3306:3306"
    networks:
      - API-UJIKOM
    volumes:
      - db_data:/var/lib/mysql

  app-laravel:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel-api
    working_dir: /var/www
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
    command: php artisan serve --host=0.0.0.0 --port=8000
    depends_on:
      - mysql-server
    networks:
      - API-UJIKOM

  phpMyadmin:
    image: phpmyadmin
    container_name: PhpMyAdmin-API
    environment:
      PMA_HOST: mysql-server
    ports:
      - "8081:80"
    depends_on:
      - mysql-server
    networks:
      - API-UJIKOM

volumes:
  db_data:

networks:
  API-UJIKOM:
    driver: bridge